### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by JSchrtke** [firtman/coffeemasters-vanilla#2]
Hey there, I just wanted to let you know that the link to the course in the README points to https://frontendmasters.com/courses/vanilla-js-apps/, which returns a 404. I came here from the recording of your workshop on FEM. That currently lives at https://frontendmasters.com/workshops/pure-javascript/. You might want to fix that, unless there soon is going to be a full course on VanillaJS on FEM ;)

**Comment by yoguib** [comment]
Hello @JSchrtke,  indeed there is a VanilaJS course on FEM: https://frontendmasters.com/courses/vanilla-js-apps/

**Comment by JSchrtke** [comment]
So there is :)
